<a href="https://colab.research.google.com/github/Sairam-DE/Python-DataEngineering/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numerical Python--NUMPY
"""

Numpy is a Python library used for working with arrays
consisting of multidimensional array objects and a collection of routines for
processing the arrays
in python we have lists that serve the purpose of arrays, but they are slow
to process
numpy aims to provide an array object which works faster than traditional python lists
numpy arrays are stored at one continuous place in memory unlike lists,
processes can access and manipulate them very efficiently


"""


In [ ]:
#installation of Mumpy
!pip install numpy

In [ ]:
#to check numpy version
import numpy
print(numpy.__version__)

1.25.2


In [ ]:
import numpy as np


CREATING ARRAYS


In [ ]:
"""
Creating Arrays

· 0-Dimensional Arrays

· 1-Dimensional Arrays

. 2-Dimensional Arrays

. 3-Dimensional Arrays
>asarray( ) with nditer( )
>frombuffer( )
>fromiter( )

""'

In [ ]:
a=np.array(69) #zero dimension
print(a)

69


In [ ]:
a=np.array([69,10,20]) #one dimension
print(a)

[69 10 20]


In [ ]:
""" tip """

#when ever there is comma in output it is list
# or
#when ever there is space it is array

In [ ]:
a=np.array([[69,79], [89,87]]) #two dimension
print(a)

[[69 79]
 [89 87]]


In [ ]:
#when ever we want to access some thing
a=np.array([[69,79], [89,87]]) #two dimension
#[69,79] -- this goes as 0 index
#[89,87] -- this goes as 1 index
a[1][0] #-- we are accessing 1 index 0th element


89

In [ ]:
a=np.array([[[10,56,87], [88,78,65]], [[66,78,77], [55,89,77]]])#--three dimension
print(a)

[[[10 56 87]
  [88 78 65]]

 [[66 78 77]
  [55 89 77]]]


In [ ]:
a[1][0][0]

66

In [ ]:
"""
here we are changing a in to array by using as array assigning it to b

and we are also describing everything by passing arguments
a=should take values in a
dtype= data type what we want
and finally printing

"""

#as array
a=[12,13,14]
b=np.asarray(a,dtype=float)
print(b)




[12. 13. 14.]


In [ ]:
#doing same thing using nditer()
# here we use other parameter
#C= ROW MAJOR ORDER
#F = COLUMN MAJOR ORDER

In [ ]:
a=[12,13,14]
b=np.asarray(a,dtype=float,order="C")
print(b)

[12. 13. 14.]


In [ ]:
#for proper visualization we use for loop
for i in np.nditer(b):
    print(i)

12.0
13.0
14.0


In [ ]:
a=[[12,13],[88,78]]
b=np.asarray(a,dtype=float,order="F")
print(b)

[[12. 13.]
 [88. 78.]]


In [ ]:
#for proper visualization we use for loop
for i in np.nditer(b):
    print(i)

12.0
88.0
13.0
78.0


In [ ]:
#from buffer - we place in buffer than we consider in to data
#b acts as buffer than the string we need
a=b"welcome to numpy"


In [ ]:
b=np.frombuffer(a,dtype="S1",count=2,offset=9)
#a=input
#string representation=S1
#COUNT = What ever the values we want
#offset= from where it to start
print(b)
#[b'o' b' ']--where "b" stands for buffer

[b'o' b' ']


In [ ]:
#from iter
a=[10,78,69,77,107]
np.fromiter(a,dtype=int,count=3)
#dtype you can take float, string as S1
#dtype=datatype function


array([10, 78, 69])

In [ ]:
"""
Initializing Array

zeros( )

full( )

random.rand( )

ones()

eye( )



Numerical Ranges

> arange( )

> linspace( )

> logspace()
"""



In [ ]:
#np.zeros -- where everything filled with zeros
a=np.zeros(3) # single dimensional array with three rows as zeros
print(a)

[0. 0. 0.]


In [ ]:
a=np.zeros([2,3])
print(a)
#here we can see 2 rows and three columns filled with zeros

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
q=np.zeros([3,7,9]) # 3 rows #7 sub strips #9columns
print(q)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
#np.full -- with what we want to fill
np.full([2,3],1)
# 2&3 rows and columns
# 1 value we need to fill


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
q=np.full([3,7],69)
print(q)

[[69 69 69 69 69 69 69]
 [69 69 69 69 69 69 69]
 [69 69 69 69 69 69 69]]


In [ ]:
q=np.full([2,3,4],77)
print(q)

[[[77 77 77 77]
  [77 77 77 77]
  [77 77 77 77]]

 [[77 77 77 77]
  [77 77 77 77]
  [77 77 77 77]]]


In [ ]:
#np.random rand -- fill with random values
np.random.rand(2,3,4)
#here no need subScript

array([[[0.49839872, 0.47227313, 0.1229174 , 0.13185227],
        [0.7682738 , 0.13309591, 0.804276  , 0.77794203],
        [0.92460045, 0.88736788, 0.66769514, 0.70914156]],

       [[0.8627815 , 0.91173461, 0.01973561, 0.28191583],
        [0.41671522, 0.03178962, 0.57381964, 0.76099306],
        [0.72770133, 0.26795795, 0.3493309 , 0.87862067]]])

In [ ]:
np.ones([2,3])
#np.ones -- everything going to fill with 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x=np.ones([2,3])
print(x)
#print 1 as float

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#np.ey -- print square matrix
np.eye(9)
#diagonal elements as 1
#remaining as 0

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
q=np.eye(6)
print(q)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


NUMERICAL RANGES

In [ ]:
q=np.arange(10,20,1)
print(q)
#starts with 10
#end before 20
#with difference 1

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
n=np.arange(88,1000,60)
print(n)


[ 88 148 208 268 328 388 448 508 568 628 688 748 808 868 928 988]


In [ ]:
g=np.arange(88,99,1,dtype=float)
print(g)
#here everything prints as float

[88. 89. 90. 91. 92. 93. 94. 95. 96. 97. 98.]


In [ ]:
#when ever we have equal division we can do reshape
#by using reshape we can convert into multidimensional


a=np.arange(10,70,10)
print(a)
k=a.reshape(2,3)
print(k)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


In [ ]:
#linspace()
h=np.linspace(10,100,10)
print(h)
#here automatically float values prints
#here endpoint get printted default
#we can avoid by endpoint=false argument
#endpoint by default true


[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
h=np.linspace(10,100,10,endpoint=False)
print(h)
#10-start
#100-stop
#10-n0.of intervals not stop

[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [ ]:
#to know difference between each value we can use
#retstep
#retstep by default false
#we need to put true when ever needed
h=np.linspace(10,100,10,endpoint=False,retstep=True)
print(h)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)


In [ ]:
#9.0--at end represents difference

In [ ]:
np.linspace(0,100,20,endpoint=False,retstep=True,dtype=int)


(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
        85, 90, 95]),
 5.0)

In [ ]:
#for logarthimetic values
np.logspace(0,10,10)
#if needed we can pass dtype=
#at end

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [ ]:
"""
Array Properties

np.size(array)

SHAPE - np.shape(array)

DTYPE - a.dtype(array) #a=array

"""

In [ ]:
a=np.arange(10,100,10)


In [ ]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.size(a) #gives no.of elements

9

In [ ]:
a=a.reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
np.size(a) #no.of elements

9

In [ ]:
np.shape(a) #will get the shape

(3, 3)

In [ ]:
a.dtype #we get the data type

dtype('int64')

In [ ]:
"""
Array Operations

Accessing and Slicing Operations
copy()

view

sort( )
reshape()

append( )
insert( )
delete( )

concatenate( )

stack()

vstack()
hstack( )
dstack( )

split( )
where()
searchsorted( )

"""

In [ ]:
#accessing
a=np.array([[10,20,78],[88,77,99]])

In [ ]:
print(a[1][0])

88


In [ ]:
#slicing

In [ ]:
x=np.arange(0,100,5)
print(x)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
x[8:12]

array([40, 45, 50, 55])

In [ ]:
#copy()
b=np.copy(x)
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
x,b

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
        85, 90, 95]),
 array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
        85, 90, 95]))

In [ ]:
#view()--act as reference


In [ ]:
a=np.array([[88,56,45],[34,54,34]])
a

array([[88, 56, 45],
       [34, 54, 34]])

In [ ]:
c=a.view()
c

array([[88, 56, 45],
       [34, 54, 34]])

In [ ]:
a[0][1]=99
a

array([[88, 99, 45],
       [34, 54, 34]])

In [ ]:
c

array([[88, 99, 45],
       [34, 54, 34]])

In [ ]:
#here you can see what ever the cahnges done to the a
#we can also see in c
#in this view is going to useful

In [ ]:
#sort()
a=np.array([88,56,45,34,54,34])
np.sort(a)


array([34, 34, 45, 54, 56, 88])

In [ ]:
a=a.reshape(2,3)
a

array([[88, 56, 45],
       [34, 54, 34]])

In [ ]:
"""
axis=0 - column wise operations
axis=1 - row wise operations

"""

In [ ]:
np.sort(a,axis=0)


array([[34, 54, 34],
       [88, 56, 45]])

In [ ]:
np.sort(a,axis=1)

array([[45, 56, 88],
       [34, 34, 54]])

In [ ]:
np.sort(a) #by default row wise sorting will take place


array([[45, 56, 88],
       [34, 34, 54]])

In [ ]:

d=np.dtype([('name','S1'), ('perc', float)])

marks=np.array([("ramu",95.0), ("hari",75.4), ("raju", 98.3) ], dtype=d)
marks

array([(b'r', 95. ), (b'h', 75.4), (b'r', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="name")

array([(b'h', 75.4), (b'r', 95. ), (b'r', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="perc")

array([(b'h', 75.4), (b'r', 95. ), (b'r', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
#reshape

In [ ]:
a=np.arange(10,130,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [ ]:
a.reshape(3,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [ ]:
#append()

In [ ]:
a=np.array([10,20,30])
a


array([10, 20, 30])

In [ ]:
b=np.array([40,50,60])
b

array([40, 50, 60])

In [ ]:
np.append(a,b).reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#insert
np.insert(a,3,35)

array([10, 20, 30, 35])

In [ ]:
#when we have multiple elements
np.insert(a,3,[66,88,67,12])

array([10, 20, 30, 66, 88, 67, 12])

In [ ]:
#can also re-shape
np.insert(a,3,[66,88,67,12]).reshape(7,1)

array([[10],
       [20],
       [30],
       [66],
       [88],
       [67],
       [12]])

In [ ]:
#delete
np.delete(a,2)

array([10, 20])

In [ ]:
#concatenate
np.concatenate((a,x),axis=0)

array([10, 20, 30,  0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65,
       70, 75, 80, 85, 90, 95])

In [ ]:
#stack
np.stack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.stack((a,b),axis=1)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
np.stack((a,b),axis=0)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.vstack((a,b)) #vertical concatenation

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.hstack((a,b)) #horizontal concatenation

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.concatenate((a,b))

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.dstack((a,b))
#first elements forms one row
#second element forms one row

array([[[10, 40],
        [20, 50],
        [30, 60]]])

In [ ]:
v=np.arange(10,180,5)
v

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175])

In [ ]:
np.split(v,2) #equal division

[array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]),
 array([ 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155,
        160, 165, 170, 175])]

In [ ]:
#multiple assignmensts
s1,s2=np.split(v,2)

In [ ]:
s1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90])

In [ ]:
s2

array([ 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155,
       160, 165, 170, 175])

In [ ]:
#TIP

#can do this on a dimension also

In [ ]:
#WHERE--able to check elements
s=np.arange(10,130,10).reshape(4,3)



In [ ]:
s

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
np.where(s==80)


(array([2]), array([1]))

In [ ]:
np.where(s%20==0)

(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))

In [ ]:
a=np.array([10,20,30,40,50,60])

In [ ]:
np.searchsorted(a,40)

3

In [ ]:
np.searchsorted(a,[40,70,50])

array([3, 6, 4])

ARITHMETIC OPERATIONS

add( )
substract( )

Multiply( )
Divide( )

Exp( )
Sqrt( )


Comparision


In [ ]:
#to perform above all operations equal dimensions are needed
#otherwise leads to error

In [ ]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[69,89,99],[101,102,102]])

In [ ]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
b

array([[ 69,  89,  99],
       [101, 102, 102]])

In [ ]:
#add
np.add(a,b)

array([[ 79, 109, 129],
       [141, 152, 162]])

In [ ]:
np.subtract(a,b) #subract

array([[-59, -69, -69],
       [-61, -52, -42]])

In [ ]:
np.multiply(a,b)

array([[ 690, 1780, 2970],
       [4040, 5100, 6120]])

In [ ]:
np.divide(a,b)

array([[0.14492754, 0.2247191 , 0.3030303 ],
       [0.3960396 , 0.49019608, 0.58823529]])

In [ ]:
#exponension takes single argument

In [ ]:
np.exp(a)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [ ]:
np.exp(b)

array([[9.25378173e+29, 4.48961282e+38, 9.88903032e+42],
       [7.30705998e+43, 1.98626484e+44, 1.98626484e+44]])

In [ ]:
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [ ]:
np.sqrt(b)

array([[ 8.30662386,  9.43398113,  9.94987437],
       [10.04987562, 10.09950494, 10.09950494]])

In [ ]:
np.array_equal(a,b) #array wise comparision

False

In [ ]:
a==b #element wise comparision

array([[False, False, False],
       [False, False, False]])

ARRAY FUNCTIONS


sum()

min()

max()
mean()

Array Functions

median(

var()

std()

In [ ]:
#from all these functions we can perform
#axis based on the requirement
#0=column
#1=row

In [ ]:
np.min(a)

10

In [ ]:
np.min(a,axis=1)

array([10, 40])

In [ ]:
np.min(a,axis=0)

array([10, 20, 30])

In [ ]:
np.sum(a)

210

In [ ]:
np.sum(a,axis=1)

array([ 60, 150])

In [ ]:
np.mean(a)

35.0

In [ ]:
np.median(a)

35.0

In [ ]:
np.var(a)

291.6666666666667

In [ ]:
np.std(a)

17.07825127659933